quarkus.http.port=8087

quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=12345678
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.jdbc.max-size=16
quarkus.http.root-path=/chat

# RabbitMQ setup

# Receive request
mp.messaging.incoming.chat-message-request.connector=smallrye-rabbitmq
mp.messaging.incoming.chat-message-request.queue=chat-message-request

# Send response
mp.messaging.outgoing.chat-message-response.connector=smallrye-rabbitmq
mp.messaging.outgoing.chat-message-response.exchange=chat-message-response
mp.messaging.outgoing.chat-message-response.routing-key=chat-message-response

# Rabbit MQ credentials
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest
